grep -v ENCFF000VSI qualified_bam.list > qualified_bam.list
grep -v ENCFF000VSJ qualified_bam.list > qualified_bam.list
grep -v ENCFF000VUC qualified_bam.list > qualified_bam.list
grep -v ENCFF000VUV qualified_bam.list > qualified_bam.list
grep -v ENCFF000VVE qualified_bam.list > qualified_bam.list
grep -v ENCFF000VVM qualified_bam.list > qualified_bam.list
grep -v ENCFF000VVT qualified_bam.list > qualified_bam.list
grep -v ENCFF000VXW qualified_bam.list > qualified_bam.list
grep -v ENCFF000VYJ qualified_bam.list > qualified_bam.list
grep -v ENCFF000WFW qualified_bam.list > qualified_bam.list
grep -v ENCFF000WFY qualified_bam.list > qualified_bam.list
grep -v ENCFF000WHE qualified_bam.list > qualified_bam.list
grep -v ENCFF216YZE qualified_bam.list > qualified_bam.list
grep -v ENCFF678NQJ qualified_bam.list > qualified_bam.list
